FROM quay.io/jupyter/pytorch-notebook:x86_64-cuda12-python-3.11.10

RUN pip install wandb

# 安装本地项目（使用可编辑模式或直接安装）
RUN pip install --force-reinstall --no-cache-dir --no-deps git+https://github.com/unslothai/unsloth.git@2025-02-v2
