name: Docker Busybox

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-shanghai.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker pull ghcr.io/element-hq/element-web:v1.12.12
          docker tag ghcr.io/element-hq/element-web:v1.12.12 registry.cn-shanghai.aliyuncs.com/yydd/busybox:element-web-v1.12.12
          # 推送镜像到镜像仓库
          docker push registry.cn-shanghai.aliyuncs.com/yydd/busybox:element-web-v1.12.12
